name       : go-for-it
version    : 1.7.3
release    : 7
source     :
    - https://github.com/JMoerman/Go-For-It/archive/1.7.3.tar.gz : 582ec27876dbfdab71c5fc681a74c3e4f5a4d0d73cd634a0c5db64e5c4c51ea7
license    : GPL-3.0-only
component  : office
summary    : A stylish to-do list with built-in productivity timer.
description: |
    Go For It! is a simple and stylish productivity app, featuring a to-do list, merged with a timer that keeps your focus on the current task.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Clean-up-the-file-name-paths.patch
    %cmake -DBUILD_TESTS=ON .
build      : |
    %make
install    : |
    %make_install
