name       : go-for-it
version    : 1.5
release    : 3
source     :
    - https://github.com/mank319/Go-For-It/archive/release_v1.5.tar.gz : 5acba45690c999f3333eb615a0217e93b53a2f9f3e36f05c006067fdb134a1f1
license    : GPL-3.0
component  : office
summary    : A stylish to-do list with built-in productivity timer.
description: |
    Go For It! is a simple and stylish productivity app, featuring a to-do list, merged with a timer that keeps your focus on the current task.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
