name       : go-for-it
version    : 1.6.9
release    : 5
source     :
    - https://github.com/JMoerman/Go-For-It/archive/1.6.9.tar.gz : 5f1ddba9261d33ee05162985448f72dd361401d8d0dbbefc31c222db249f0a66
license    : GPL-3.0
component  : office
summary    : A stylish to-do list with built-in productivity timer.
description: |
    Go For It! is a simple and stylish productivity app, featuring a to-do list, merged with a timer that keeps your focus on the current task.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Clean-up-the-file-name-paths.patch
    %cmake -DBUILD_TESTS=ON .
build      : |
    %make
install    : |
    %make_install
